main_page/urls.py
from django.conf.urls import url

from . import views

app_name = 'main_page'

urlpatterns = (
    url(r'^$', views.index, name='index'),

    url(r'^about/$', views.about, name='about'),
    url(r'^add_issue/$', views.addIssue, name='add_issue'),
    url(r'^add_heading(?P<pk>[0-9]+)/$', views.addHeading, name='add_heading'),
    url(r'^article(?P<pk>[0-9]+)/$', views.article_view, name='article'),
    url(r'^article-premoderation/(?P<pk>[0-9]+)/$', views.article_premoderation_view,
        name='article-premoderation-view'),

    url(r'^delete_article/(?P<pk>[0-9]+)/$', views.delete_article, name='delete_article'),
    url(r'^download(?P<pk>[0-9]+)/$', views.download, name='download'),
    url(r'^send_comment$', views.send_comment, name='send_comment'),
    url(r'^delete_comment/(?P<pk>\d+)$', views.delete_comment, name='delete_comment'),
    url(r'^delete_user(?P<pk>\d+)$', views.delete_user, name='delete_user'),

    url(r'^list/$', views.list_article, name='list_page'),
    url(r'^list(?P<stat>[-\w.]{3})/$', views.list_article, name='list_page'),
    url(r'^list(?P<heading_pk>[0-9]+)/$', views.list_article, name='list_article'),
    url(r'^list_issue/$', views.list_issue, name='list_issue'),
    url(r'^list_heading(?P<issue_pk>[0-9]+)/$', views.list_heading, name='list_heading'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.LogOutView.as_view(), name='logout'),

    url(r'^main-page-edit/$', views.main_page_edit, name='main-page-edit'),

    url(r'^profile/$', views.update_profile, name='profile'),
    url(r'^profile/(?P<username>[-\w.]+)$', views.show_profile, name='show_profile'),
    url(r'^premoderation-article-list/$', views.premoderation_article_list, name='premoderation-article-list'),
    url(r'^pub_article/(?P<pk>[0-9]+)/$', views.pub_article, name='pub_article'),

    url(r'^search-author/$', views.search_author, name='search-author'),
    url(r'^search-author/(?P<author>[-\w.]+)$', views.list_by_author, name='list_by_author'),
    url(r'^send_article/$', views.send_article, name='send_article'),
    url(r'^send_content/(?P<article_pk>[0-9]+)/$', views.send_content, name='send_content'),
    url(r'^signup/$', views.RegisterFormView.as_view(), name='signup'),
    #password_reset urls
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),


    url(r'^urls/$', views.all_urls, name='all_urls'),
)

scienceJournal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from main_page.views import main_page_redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main_page_redirect),
    url(r'^main/', include('main_page.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_page/forms.py
from django.contrib.auth.models import User
from bootstrap3_datetime.widgets import DateTimePicker
from django.forms import *
from .models import *
from ckeditor.fields import CKEditorWidget

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ('cover', 'heading', 'article_title', 'description', 'references', 'wac', 'thanks')
        labels = {
            'cover': 'Обложка',
            'heading': 'Заголовок',
            'article_title': 'Название',
            'description': 'Описание',
            'references': 'Источники',
            'wac': 'WAC',
            'thanks': 'Благодарности',
        }


class ArticleContentForm(ModelForm):
    class Meta:
        model = ArticleContent
        fields = ('content',)
        labels = {
            'content': 'Файл статьи',
        }
        
    def cleaned_file(self):
        file = self.cleaned_data['content']
        error = None
        try:
            if file:
                file_type = file.content_type.split('/')[1]
            if len(file.name.split('.')) == 1:
                error = 'Данный формат не поддерживается'

            if file_type in settings.ARTICLE_CONTENT_TYPE:
                if file._size > settings.ARTICLE_MAX_SIZE:
                    error = 'Размер файла превышен'
            else:
                error = 'Данный формат не поддерживается'
        except:
            pass

        if error:
            return error
        else:
            return file


class IssueForm(ModelForm):
    class Meta:
        model = Issue
        fields = ('num', 'cover')


class HeadingForm(ModelForm):
    class Meta:
        model = Heading
        fields = ('heading',)


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Email',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('body', 'article')


class ProfileForm(ModelForm):
    birth_date = DateField(input_formats=settings.DATE_INPUT_FORMATS,
                          widget=DateTimePicker(options={"format": "DD-MM-YYYY", "pickTime": False}))
    additionalInfo = CharField(widget=CKEditorWidget())

    class Meta:
        model = Profile
        fields = ('patronymic', 'avatar', 'birth_date', 'additionalInfo')
        labels = {
            'patronymic': 'Отчество',
            'additionalInfo': 'Дополнительная информация',
        }


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ['body']
        labels = {
            'body': 'Введите причину отказа к публикации статьи',
        }


class MainPageInfoForm(ModelForm):
    class Meta:
        model = MainPageInfo
        fields = ['appeal', 'greetings', 'whatIsNew']
        labels = {
            'greetings': 'Приветствие',
            'appeal': 'Обращение разработчиков',
            'whatIsNew': 'Что нового',
        }

main_page/views.py
import os.path

from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.edit import FormView
from libs.display_exceptions import NotFound
from django.shortcuts import resolve_url
from django.template.response import TemplateResponse
from django.contrib.auth.tokens import default_token_generator
from django.views.decorators.csrf import csrf_protect
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters

from .forms import *  # для формы
from .models import Article, Issue, Heading, ArticleContent, Comment, MainPageInfo
from django.conf.urls import RegexURLPattern, RegexURLResolver
from django.core.exceptions import ObjectDoesNotExist


class LogOutView(generic.RedirectView):
    url = reverse_lazy('main_page:index')

    def get(self, request, *args, **kwargs):
        logout(self.request)
        return super(LogOutView, self).get(self.request, *args, **kwargs)


class RegisterFormView(FormView):
    form_class = UserCreationForm

    # Ссылка, на которую будет перенаправляться пользователь в случае успешной регистрации.
    # В данном случае указана ссылка на страницу входа для зарегистрированных пользователей.
    success_url = reverse_lazy('main_page:profile')

    # Шаблон, который будет использоваться при отображении представления.
    template_name = "form.html"

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
        if user is not None:
            login(self.request, user)
        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)


def about(request):
    context = {'page_name': 'about'}
    return render(request, './about.html', context)


def addIssue(request):
    if request.method == 'POST':
        form = IssueForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('main_page:list_issue')
    else:
        form = IssueForm()
    return render(request, './form.html', {'form': form, 'page_name': 'add_issue'})


def addHeading(request, pk):
    if request.method == 'POST':
        form = HeadingForm(request.POST)
        if form.is_valid():
            heading = form.save(commit=False)
            heading.issue = Issue.objects.get(pk=pk)
            heading.save()
            return redirect('main_page:list_heading', issue_pk=pk)
    else:
        form = HeadingForm()
    return render(request, './form.html', {'form': form, 'page_name': 'add_heading'})


def all_urls(request):
    from .urls import urlpatterns  # this import should be inside the function to avoid an import loop
    nice_urls = get_urls(urlpatterns)  # build the list of urls recursively and then sort it alphabetically
    return render(request, "all_urls.html", {"links": nice_urls})


def delete_user(request, pk):
    User.objects.get(pk=pk).delete()
    return redirect('main_page:index')


def main_page_redirect(request):
    return redirect('/main/')


def show_profile(request, username):
    try:
        user = User.objects.get(username=username)
        profile = user.profile
        return render(request, 'show_profile.html', {'profile': profile})
    except ObjectDoesNotExist:
        raise NotFound('User not found!.', next=resolve_url(request.META.get('HTTP_REFERER', 'main_page:index')))


def article_premoderation_view(request, pk):
    article_content = ArticleContent.objects.filter(article=Article.objects.get(pk=pk)).get(latest_version=True)
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = User.objects.get(pk=request.user.id)
            new_comment.article_content = article_content
            new_comment.save()
            article = article_content.article
            article.status = 'MOD'
            article.save()
        return redirect('main_page:index')
    else:
        form = FeedbackForm()
    return render(request, 'article.html',
                  {'article': article_content.article, 'page_name': 'article-premoderation', 'premoderation': 1,
                   'form': form})


def article_view(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'article.html', {'article': article, 'page_name': 'article', 'user': request.user,
                                            'comments': Comment.objects.filter(article=pk)})


def delete_article(request, pk):
    Article.objects.get(pk=pk).delete()
    return redirect('main_page:list_page')


def delete_comment(request, pk):
    Comment.objects.get(pk=pk).delete()
    return redirect(request.META.get('HTTP_REFERER', 'main_page:index'))


def download(request, pk):
    art = ArticleContent.objects.get(article=Article.objects.get(pk=pk), latest_version=True)
    file_name = os.path.basename(art.content.path)
    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=' + file_name
    response['X-Sendfile'] = file_name
    return response


def get_urls(raw_urls, nice_urls=[], urlbase=''):
    '''Recursively builds a list of all the urls in the current project and the name of their associated view'''
    from operator import itemgetter
    for entry in raw_urls:
        fullurl = entry.regex.pattern.replace('^', '')
        viewname = entry.name
        # split_fullurl = entry.regex.pattern.split('/', fullurl)
        # split_fullurl = fullurl[:fullurl.find('/', '(')]
        split_fullurl = fullurl.split('/')
        split_fullurl = split_fullurl[0].split('$')
        split_fullurl = split_fullurl[0].split('(')
        # print(fullurl)
        nice_urls.append({"name": viewname, "pattern": split_fullurl[0]})
    nice_urls = sorted(nice_urls, key=itemgetter('pattern'))  # sort alphabetically
    return nice_urls


def index(request):
    MainPage = {'header': "Tough Life",
                'headerDescription': "Официальная страница научного журнала",
                'aboutHeader': "О журнале",
                'aboutText': "Журнал является прототипом научного журнала в вакууме. Никаких научных статей. Разработчики: Бутолин Дмитрий, Гильмитдинов Ноэль, Шавлюк Михаил и Леха.",
                'archivesHeader': "Архив",
                'elsewhereHeader': "Мы в социальных сетях"}
    MainPageDBInfo = MainPageInfo.objects.last()
    context = {'MainPage': MainPage, 'page_name': 'index', 'MainPageDBInfo': MainPageDBInfo}
    return render(request, 'index.html', context)


def list_article(request, heading_pk=None, stat='pub'):
    if heading_pk == None:
        articles = Article.objects.filter(status=stat.upper())
    else:
        articles = Article.objects.filter(heading=Heading.objects.get(pk=heading_pk)).filter(status=stat.upper())
    context = {'page_name': 'list_page', 'articles': articles}
    return render(request, 'list_page.html', context)


def list_by_author(request, author):
    try:
        author = User.objects.get(username=author)
        articles = Article.objects.filter(authors=author)
    except:
        raise NotFound('Error.', next=resolve_url('main_page:search-author'))
    context = {'page_name': 'list_page', 'articles': articles}
    return render(request, 'list_page.html', context)


def list_heading(request, issue_pk):
    headings = Heading.objects.filter(issue=Issue.objects.get(pk=issue_pk))
    context = {'page_name': 'list_heading', 'headings': headings, 'issue': Issue.objects.get(pk=issue_pk)}
    return render(request, './list_heading.html', context)


def list_issue(request):
    issues = Issue.objects.all()
    context = {'page_name': 'list_issue', 'issues': issues}
    return render(request, './list_issue.html', context)


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse_lazy('main_page:index'))
        else:
            raise NotFound('A username is needed to look up a user.', next=resolve_url('main_page:index'))
    else:  # Отображаем страницу входа
        ...


def pub_article(request, pk):
    article = Article.objects.get(pk=pk)
    article.status = 'PUB'
    article.save()
    return redirect('main_page:list_page')


def premoderation_article_list(request):
    articles = Article.objects.filter(status='PRM')
    context = {'page_name': 'premoderation-article-list', 'articles': articles}
    return render(request, './premoderation_article_list.html', context)


def page_not_found_view(request):
    raise NotFound('Page not found!.', next=resolve_url('main_page:index'))


def send_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.authors = User.objects.get(pk=request.user.id).username
            article.save()
            return HttpResponseRedirect(reverse_lazy('main_page:send_content', kwargs={'article_pk': article.pk}))
    else:
        form = ArticleForm()
    return render(request, './send_article.html', {'form': form, 'page_name': 'send_article'})


def send_content(request, article_pk):

main_page/templates/article.html
{% extends 'base.html' %}

{% block title %} {{ article.article_title }} | {{ block.super }} {% endblock %}
{% load static %}
    <script type="text/javascript" src="{% static "js/profile/img_resize.js" %}"></script>


{% block css %}
    <link href="{% static 'css/comment.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    {% load bootstrap_tags %}


    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
            <div class="jumbotron">
                <h1>{{ article.article_title }}</h1>
                <h3>Автор: {{ article.authors }}</h3>
            </div>
            <p> Дата загрузки: {{ article.pub_date|date }} </p>
            <p> Опиcание: {{ article.description }} </p>
            <p> WAC: {{ article.wac }} </p>
            <p> Благодарности: {{ article.thanks }} </p>
            <p> Референсы: {{ article.references }} </p>
            <br/>
            <a class="btn btn-primary" href="{% url 'main_page:download' article.pk %}">Скачать</a>

            {% if premoderation %}
                {% if user.is_superuser %}
                    {#                    todo Перенести в отдельную функцию#}
                    <form action="{% url 'main_page:pub_article' article.pk %}"
                          method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <button class="btn btn-success" id="id_success" name="name_success">Опубликовать
                        </button>
                    </form>
                    <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal">Отклонить
                    </button><br>
                    <a href="{% url 'main_page:delete_article' article.pk %}" class="btn btn-danger">Удалить</a>

                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Отказ в публикации</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'main_page:article-premoderation-view' article.pk %}"
                                          method="post"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form|as_bootstrap }}
                                        <button class="btn btn-danger" type="submit" id="article_decline"
                                                name="Подтвердить">Подтвердить
                                        </button>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                                </div>
                            </div>

                        </div>
                    </div>

                {% endif %}
            {% endif %}

            <div class="comments-content">
                <div id="comment-holder">
                    <div u="x" t="x" kind="x" class="comment-thread" id="xxx">
                        <ol id="xxx">
                            {% for comment in comments %}
                            <li kind="x" class="comment" id="xxx">
                                <div class="avatar-image-container">
                                    <img src="{% static comment.user.profile.avatar %}">
                                </div>
                                <div class="comment-block" id="xxx">
                                    <div kind="x" class="comment-header" id="xxx">
                                        <cite class="user"><a href="xxxx" rel="nofollow">{{ comment.user.username }}</a></cite>
                                        <span class="icon user"> </span>
                                        <span class="datetime secondary-text"><a href="xxx"
                                                                                 rel="nofollow">{{ comment.date }}</a></span>
                                    </div>
                                    <p class="comment-content" id="xxx">{{ comment.body }}</p>
                                    <span kind="x" class="comment-actions secondary-text" id="xxx">
                                     <a data-original-title="Reply" data-toggle="tooltip" type="button"
                                        class="btn btn-sm btn-info"><i class="glyphicon glyphicon-comment"></i></a>
                                     <a data-original-title="Delete" data-toggle="tooltip" type="button"
                                        class="btn btn-sm btn-danger" href="{% url 'main_page:delete_comment' comment.pk %}"><i class="glyphicon glyphicon-remove"></i></a>
                                 </span>
                                </div>
                                {% comment "comment-reply" %}
                             <div class="comment-replies" id="xxx">
                                 <span kind="x" id="xxx">
                                     <div u="x" t="x" kind="x" class="comment-thread inline-thread" id="xxx">
                                         <span kind="x" class="thread-toggle thread-expanded" id="xxx">
                                             <span class="thread-arrow" id="xxx"></span>
                                             <span class="thread-count" id="xxx">
                                                 <span style="display: none;" id="xxx"></span>
                                                 <span style="display: none;" id="xxx"></span>
                                                 <a target="_self" href="javascript:;">Replies</a>
                                                 <div class="thread-dropContainer thread-expanded" id="xxx">
                                                     <span class="thread-drop"></span>
                                                 </div>
                                             </span>
                                         </span>
                                         <ol class="thread-chrome thread-expanded" id="xxx">
                                             <div>
                                                 <li kind="b" class="comment" id="xxx">
                                                     <div class="avatar-image-container">
                                                         <img src="avatar of people who reply comment above">
                                                     </div>
                                                     <div class="comment-block" id="xxx">
                                                         <div kind="m" class="comment-header" id="xxx">
                                                             <cite class="user blog-author"><a href="xxx" rel="nofollow">name of people who reply comment</a></cite>
                                                             <span class="icon user blog-author"></span>
                                                             <span class="datetime secondary-text"><a href="xxx" rel="nofollow">date and time reply comment</a></span>
                                                         </div>
                                                         <p class="comment-content" id="xxx">comment body</p>
                                                         <span kind="m" class="comment-actions secondary-text" id="xxx">
                                                             <span class="item-control blog-admin pid-868019743"><a href="xxx" target="_self" o="d">Delete</a></span>
                                                         </span>
                                                     </div>
                                                     <div class="comment-replies" id="xxx"></div>
                                                     <div class="comment-replybox-single" id="xxx"></div>
                                                 </li>
                                             </div>
                                             <div kind="ci" class="continue" id="xxx"><a target="_self" href="javascript:;">Reply</a></div>
                                         </ol>
                                         <div class="comment-replybox-thread" id="xxx"></div>
                                     </div>
                                 </span>
                             </div>
                             {% endcomment %}
                                <div class="comment-replybox-single" id="xxx"></div>
                            </li>
                            {% endfor %}

                            <li kind="x" class="comment" id="xxx">
                                <div class="avatar-image-container">
                                    <img src="{% static user.profile.avatar %}">
                                </div>
                                <div class="form-group comment-block">
                                    <div kind="x" class="comment-header" id="xxx">
                                        <cite class="user"><a href="xxxx" rel="nofollow">Admin</a></cite>
                                        <span class="icon user"> </span>
                                        <span class="datetime secondary-text"><a href="xxx"
                                                                                 rel="nofollow">March 24, 2017</a></span>
                                </div>
                                <form method="post" action="{% url "main_page:send_comment" %}">
                                    {% csrf_token %}
                                    <textarea class="form-control" name="body" rows="3" id="comment"></textarea>
                                    <input type="submit" value="Отправить" class="btn btn-sm btn-info">
                                    <input type="hidden" name="article" value="{{ article.pk }}">
                                </form>
                                </div>
                                <div class="comment-replybox-single" id="xxx"></div>
                            </li>
                        </ol>
                        {% comment "comment-others" %}
                     <div kind="ci" class="continue" id="xxx" style="display: none;">
                         <a target="_self" href="javascript:;">Add comment</a>
                     </div>
                     <div class="comment-replybox-thread" id="xxx">
                         xxxxxxxxx
                     </div>
                     <div kind="rb" class="loadmore loaded" id="xxx"><a target="_self" href="javascript:;">Load more...</a></div>
                 </div>
                 {% endcomment %}

                    </div>

                </div>

            </div>
            </div>
        </div>
{% endblock content %}

main_page/templates/base.html
{% load static %}
{% load bootstrap_tags %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="{% static 'css/main_page.css' %}" rel="stylesheet">
    {% load bootstrap_tags %}
    {% block css %}{% endblock css %}

    {% block js_begin %}
        <script src="{% static 'js/frameworks/jquery.min.js' %}"></script>
        <script src="{% static 'js/frameworks/bootstrap.js' %}"></script>
    {% endblock js_begin %}
    <title>{% block title %} JOURNAL $666 {% endblock title %}</title>
</head>


<body>
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item {% if page_name == "index" %} active {% endif %}"
               href="{% url 'main_page:index' %}">Домой</a>
            <a class="blog-nav-item {% if page_name == "search-author" %} active {% endif %}"
               href="{% url 'main_page:search-author' %}">Поиск</a>
            <a class="blog-nav-item {% if page_name == "list_page" or page_name == "list_issue" or page_name == "list_heading" %} active {% endif %}"
               href="{% url 'main_page:list_issue' %}">Все журналы</a>
            {% if user.is_superuser %}
                <a class="blog-nav-item {% if page_name == "premoderation-article-list" %} active {% endif %}"
                   href="{% url 'main_page:premoderation-article-list' %}">Премодерация</a>
                <a class="blog-nav-item {% if page_name == "main-page-edit" %} active {% endif %}"
                   href="{% url 'main_page:main-page-edit' %}">Изменение контента главной страницы</a>

            {% endif %}
            <a class="blog-nav-item {% if page_name == 'about' %} active {% endif %}"
               href="{% url 'main_page:about' %}">О журнале</a>

            {% if not user.is_authenticated %}
                <form class="navbar-form navbar-right" action="{% url 'main_page:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" placeholder="Логин" class="form-control" name="username">
                        <input type="password" placeholder="Пароль" class="form-control" name="password">
                    </div>
                    <button type="submit" class="btn btn-success">
                        Войти
                    </button>
                </form>
                <a class="blog-nav-item {% if page_name == "signup" %} active {% endif %}"
                   href="{% url 'main_page:signup' %}">Зарегестрироваться</a>
            {% else %}
                <a class="blog-nav-item {% if page_name == "send_article" %} active {% endif %}"
                   href="{% url 'main_page:send_article' %}">Отправить статью</a>
                <a class="blog-nav-item" href="{% url 'main_page:profile' %}">Вы вошли как {{ user.username }}</a>

                <a class="blog-nav-item" href="{% url 'main_page:logout' %}">Выйти</a>

            {% endif %}
        </nav>
    </div>
</div>
{% block content %}
    Content here
{% endblock content %}
<footer class="blog-footer">
    <p>Tough Life Magazine 2016</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>
{% block js_end %}
    <script src="{% static 'js/other/logs.js' %}"></script>
    <script src="{% static 'js/search_author/form.js' %}"></script>
{% endblock js_end %}
</body>

main_page/templates/error.html
{% extends 'base.html' %}
{% block title %} Main Page | {{ block.super }} {% endblock %}

{% block content %}
<div class="container">
    {{ message }}
</div><!-- /.container -->

{% endblock %}

main_page/templates/main-page-edit.html
{% extends './base.html' %}
{% block title %} Main Page | {{ block.super }} {% endblock %}
{% load bootstrap_tags %}
{% block content %}
    <div class="container">
        <div class="modal-dialog">
            <form action="{% url 'main_page:main-page-edit' %}" method="post">
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <input type="submit" value="Отправить" class="btn btn-primary"/>
            </form>
        </div>
    </div>
{% endblock %}